services:
  postgres-organization:
    image: postgres:16
    container_name: postgres-organization
    # restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-organization-data:/var/lib/postgresql/data
    networks:
      - participants-service_ecs_microservices_network

  nest-ecs-organization:
    container_name: nest-ecs-organization
    build:
      context: .
      args:
        DATABASE_URL: $DATABASE_URL
        PORT: $PORT
        TCP: $TCP
        PATIENT_HOST: $PATIENT_HOST
        PATIENT_PORT: $PATIENT_PORT
      dockerfile: ./Dockerfile
      target: development
    command: sh -c "npx prisma migrate dev && npm run start:dev"
    env_file:
      - .env
    ports:
      - '4000:$PORT'
      - '4001:$TCP'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres-organization
    networks:
      - participants-service_ecs_microservices_network

volumes:
  postgres-organization-data:

networks:
  participants-service_ecs_microservices_network:
    external: true
